spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SMSServer?useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123456
  jpa:
    generate-ddl: true
    properties:
      hibernate.ddl-auto: CREATE
      jpa.show-sql: true

server:
  port: 8081
